version: '3.8'

services:
  fastapi:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=rootpassword 
      - DB_HOST=db
      - DB_NAME=api_pedidos

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: api_pedidos
    ports:
      - "5432:5432"
    volumes:
      - ./api_pedidos.sql:/docker-entrypoint-initdb.d/api_pedidos.sql
